### PR TITLE
Gsoc2018 aos 2 demo parijit

### PR DESCRIPTION
**Pull request by parijitkedia**
integrating the branch

### CODE REVIEW

**Comment by sloriot** [comment]
I guess this is a mistake so I close this PR.

**Comment by lrineau** [comment]
@parijitkedia You can push directly into the repository `CGAL/cgal-public-dev`, to a given branch, or to a new branch you create.

**Comment by parijitkedia** [comment]
I dont have permissions to push. So could you please grant me one

**Comment by sloriot** [comment]
Of course, your invitation is still pending. It means you did not have accepted it. Look at your spam box. You maybe even should see it when you log into github. You might also see it here: https://github.com/settings/organizations

**Pull request closed without merging**
